"use strict";
exports.__esModule = true;
var express_1 = require("express");
var user_1 = require("../controllers/user");
var client_1 = require("../controllers/client");
var product_1 = require("../controllers/product");
var salesOrder_1 = require("../controllers/salesOrder");
var login_1 = require("../controllers/login");
var authentication_1 = require("../middlewares/authentication");
var router = express_1["default"].Router();
router.post('/login', login_1.signIn);
router.use(authentication_1.authentication);
router.get('/users', user_1.getUsers);
router.get('/users/:id', user_1.getUser);
router.post('/users', user_1.postUser);
router.put('/users/:id', user_1.updateUser);
router["delete"]('/users/:id', user_1.deleteUser);
router.get('/clients', client_1.getClients);
router.get('/clients/:companyName', client_1.getClient);
router.post('/clients', client_1.postClient);
router.put('/clients/:id', client_1.updateClient);
router["delete"]('/clients/:id', client_1.deleteClient);
router.get('/products', product_1.getProducts);
router.get('/products/:name', product_1.getProduct);
router.post('/products', product_1.postProduct);
router.put('/products/:id', product_1.updateProduct);
router["delete"]('/products/:id', product_1.deleteProduct);
router.get('/sales-orders', salesOrder_1.getSalesOrders);
router.post('/sales-orders', salesOrder_1.postSalesOrder);
router.put('/sales-orders/:id', salesOrder_1.updateSalesOrder);
router["delete"]('/sales-orders/:id', salesOrder_1.deleteSalesOrder);
exports["default"] = router;
